---

- name: setup the mariadb database server
  hosts: db_hosts

  tasks:

    - name: ensure tasks run only on selected os releases
      block:

        - name: register system to satellite
          ansible.builtin.include_role:
            name: verbose_doodle
            tasks_from: db_setup.yml

      when: ansible_distribution == "RedHat"

...
