---

- name: configure vm baseline setup
  hosts: "{{ nodes }}"

  tasks:

    - name: deploy baseline configuration
      ansible.builtin.include_role:
        name: number_cruncher
        tasks_from: baseline.yml

...
