---

- name: deploy the mariadb database server
  hosts: db_hosts

  tasks:

    - name: ensure tasks run only on selected os releases
      block:

        - name: deploy the mariadb server
          ansible.builtin.include_role:
            name: verbose_doodle
            tasks_from: db_setup.yml

      when: ansible_distribution == "RedHat"

- name: deploy the phpmyadmin application
  hosts: web_hosts

  tasks:

    - name: ensure tasks run only on selected os releases
      block:

        - name: deploy the phpmyadmin webapp
          ansible.builtin.include_role:
            name: verbose_doodle
            tasks_from: web_setup.yml

      when: ansible_distribution == "RedHat"

#- name: deploy the nginx load balancer
#  hosts: lb_hosts

#  tasks:

#    - name: ensure tasks run only on selected os releases
#      block:

#        - name: deploy the nginx balancer
#          ansible.builtin.include_role:
#            name: verbose_doodle
#            tasks_from: lb_setup.yml

#      when: ansible_distribution == "RedHat"

...
